import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      /*
       * Fast Refresh needs a module to export components only, so that editing
       * one can be hot-swapped without losing state. `allowConstantExport` makes
       * room for the one exception that is everywhere in this codebase: a
       * component file that also exports a frozen constant next to it - a cva
       * variant table, a label map. Those cannot change at runtime, so swapping
       * the module is still safe, and splitting each one into its own file to
       * satisfy the linter would scatter a label away from the badge that uses it.
       */
      'react-refresh/only-export-components': ['error', { allowConstantExport: true }],
    },
  },
  {
    /*
     * Vendored code, held to its upstream shape rather than to ours.
     *
     * components/ui is shadcn's output and is regenerated by its CLI;
     * modules/data-analyst-agent was ported wholesale from another application.
     * Reformatting either to satisfy a lint rule means re-doing that work on
     * every update, and the rule switched off here - Fast Refresh granularity -
     * costs a component remount during development and nothing in production.
     */
    files: ['src/components/ui/**/*.{ts,tsx}', 'src/modules/data-analyst-agent/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
