import { useState } from 'react'
import { Loader2, RefreshCw, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { notify } from '@/components/common/notify'
import { StepFrame } from '../../components/StepFrame'
import {
  EmptyState,
  ErrorState,
  NoConnectionState,
  QueryBoundary,
  TableSkeleton,
} from '../../components/DataStates'
import { SectionHeading, StatTile } from '../../components/primitives'
import { formatRelativeTime } from '../../components/format'
import { endpoints } from '../../api'
import { useGenerateUnderstanding, useUnderstanding } from '../../queries/hooks'
import { useWorkflow } from '../../state/workflowContext'
import { BlockRenderer } from './blocks'
import type { Understanding } from '../../types'

/**
 * Step 4 — Understand. The first AI-produced step.
 *
 * Everything on this screen is generated by the backend and rendered
 * dynamically: the tabs are sections the backend named, the tiles are counts it
 * reported, and each card is a typed block drawn by `BlockRenderer`. The
 * frontend contributes no business vocabulary at all.
 *
 * Generation is explicit rather than automatic. A run costs real time and
 * money, so opening the step reads whatever exists and offers to generate;
 * while a run is in flight the query polls `status` until it settles.
 */
export function UnderstandStep() {
  const { connectionId, goToStep } = useWorkflow()
  const understanding = useUnderstanding(connectionId)
  const generate = useGenerateUnderstanding(connectionId)

  if (!connectionId) {
    return (
      <StepFrame title="Understand your data" hideNext>
        <NoConnectionState onConnect={() => goToStep('connect')} />
      </StepFrame>
    )
  }

  const runGeneration = async () => {
    try {
      await generate.mutateAsync()
      notify.success('Analysis started.', 'This screen updates as it progresses.')
    } catch (err) {
      notify.failure('start the analysis', err)
    }
  }

  return (
    <StepFrame
      title="Understand your data"
      description="The backend analyses the profiled datasets and generates business context, definitions and insights."
      actions={
        <Button
          variant="outline"
          size="sm"
          onClick={runGeneration}
          disabled={generate.isPending || understanding.data?.status === 'generating'}
        >
          {generate.isPending || understanding.data?.status === 'generating' ? (
            <Loader2 className="size-4 animate-spin" aria-hidden />
          ) : (
            <RefreshCw className="size-4" aria-hidden />
          )}
          {understanding.data?.generatedAt ? 'Regenerate' : 'Generate'}
        </Button>
      }
      footerNote={
        understanding.data?.generatedAt
          ? `Generated ${formatRelativeTime(understanding.data.generatedAt)}${
              understanding.data.model ? ` · ${understanding.data.model}` : ''
            }`
          : undefined
      }
    >
      <QueryBoundary
        query={understanding}
        step="Understand"
        endpoint={`GET ${endpoints.understanding(connectionId)}`}
        context="load the generated understanding"
        loading={<TableSkeleton rows={5} columns={3} />}
      >
        {(data) => <UnderstandingView data={data} onGenerate={runGeneration} />}
      </QueryBoundary>
    </StepFrame>
  )
}

function UnderstandingView({
  data,
  onGenerate,
}: {
  data: Understanding
  onGenerate: () => void
}) {
  const [section, setSection] = useState<string | undefined>(undefined)

  if (data.status === 'generating') {
    return (
      <div className="flex flex-col items-center justify-center rounded-lg border border-dashed px-6 py-16 text-center">
        <Loader2 className="mb-4 size-6 animate-spin text-primary" aria-hidden />
        <p className="text-sm font-medium">Analysing your data</p>
        <p className="mt-1 max-w-md text-sm text-muted-foreground">
          The backend is reading the profiled tables and generating business context. This screen
          updates on its own when the run finishes.
        </p>
      </div>
    )
  }

  if (data.status === 'failed') {
    return (
      <ErrorState
        context="generate the understanding"
        error={new Error(data.error ?? 'The analysis did not complete.')}
        onRetry={onGenerate}
      />
    )
  }

  if (data.status === 'pending' || data.sections.length === 0) {
    return (
      <EmptyState
        title="No analysis yet"
        detail="Generate an analysis to produce business definitions, metrics and insights from the datasets you profiled."
        action={
          <Button size="sm" onClick={onGenerate}>
            <Sparkles className="size-4" aria-hidden />
            Generate analysis
          </Button>
        }
      />
    )
  }

  const active = section ?? data.sections[0]?.id

  return (
    <div className="space-y-5">
      {data.stats.length > 0 ? (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {data.stats.map((stat) => (
            <StatTile
              key={stat.id}
              label={stat.label}
              value={stat.value}
              hint={stat.hint}
              // A tile links to its section only when the backend says which.
              onClick={stat.sectionId ? () => setSection(stat.sectionId!) : undefined}
            />
          ))}
        </div>
      ) : null}

      <Tabs value={active} onValueChange={setSection}>
        <TabsList className="flex-wrap">
          {data.sections.map((s) => (
            <TabsTrigger key={s.id} value={s.id}>
              {s.title}
            </TabsTrigger>
          ))}
        </TabsList>

        {data.sections.map((s) => (
          <TabsContent key={s.id} value={s.id} className="mt-4">
            {s.blocks.length === 0 ? (
              <EmptyState title="Nothing in this section" />
            ) : (
              <div className="grid gap-3 lg:grid-cols-2">
                {s.blocks.map((block) => (
                  <BlockRenderer key={block.id} block={block} />
                ))}
              </div>
            )}
          </TabsContent>
        ))}
      </Tabs>

      {data.sampleQuestions.length > 0 ? (
        <section>
          <SectionHeading
            title="Sample questions"
            description="What the published context will be able to answer."
          />
          <div className="flex flex-wrap gap-2">
            {data.sampleQuestions.map((question, i) => (
              <span
                key={i}
                className="rounded-full border bg-card px-3 py-1.5 text-sm text-muted-foreground"
              >
                {question}
              </span>
            ))}
          </div>
        </section>
      ) : null}
    </div>
  )
}
