import { contextHttp } from './client'
import { endpoints } from './endpoints'
import type { Understanding } from '../types'

/**
 * Step 4 — Understand. PROPOSED: these routes are not built yet.
 *
 * The first AI-produced step. Everything it renders — business definitions,
 * metrics, dimensions, entities, quality observations, sample questions — is
 * generated by the backend from the profiled data and returned as a list of
 * typed blocks.
 *
 * Nothing about the content is known to the frontend. There is no list of
 * expected metric names, no fallback definition, no placeholder term: the
 * renderer switches on `block.type` and draws whatever came back, including a
 * visible "unsupported block" card for a type it does not recognise. That is
 * what makes a new kind of AI output a backend-only change.
 *
 * Generation is a separate POST from the read, because it is slow and because
 * re-running it is a decision somebody makes rather than a side effect of
 * opening a page. `status` on the read reports where that run has got to.
 */

export function fetchUnderstanding(connectionId: string): Promise<Understanding> {
  return contextHttp.get<Understanding>(endpoints.understanding(connectionId))
}

/**
 * Asks for a fresh run.
 *
 * Returns the same shape as the read, so a caller can seed the cache with it —
 * typically `status: 'generating'`, which the read then polls until it settles.
 */
export function generateUnderstanding(connectionId: string): Promise<Understanding> {
  return contextHttp.post<Understanding>(endpoints.generateUnderstanding(connectionId))
}
